SELECT COLUMN_NAME AS 'Column',
       COLUMN_TYPE AS 'Type',
       IS_NULLABLE AS 'Null',
       COLUMN_KEY AS 'Key',
       COLUMN_DEFAULT AS 'Default',
       EXTRA AS 'Extra'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Books'
  AND TABLE_SCHEMA = DATABASE()
ORDER BY ORDINAL_POSITION;
